# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-05 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretakerinfo',
            old_name='experience',
            new_name='jobExperience',
        ),
    ]
