# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-11 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181111_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('Pet_Me_Questions', 'Pet-Me-Questions'), ('General Question', 'General-Question')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
