# Generated by Django 2.0 on 2018-11-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_faq_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='favoriteThings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoriteThings', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Ajman', 'Ajman'), ('Sharjah', 'Sharjah'), ('Dubai', 'Dubai'), ('Fujairah', 'Fujairah'), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Umm Al Quwain', 'Umm al Quwain')], max_length=300),
        ),
        migrations.AlterField(
            model_name='address',
            name='doorNo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='emirate',
            field=models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Ajman', 'Ajman'), ('Sharjah', 'Sharjah'), ('Dubai', 'Dubai'), ('Fujairah', 'Fujairah'), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Umm Al Quwain', 'Umm al Quwain')], max_length=300),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('Pet-Me-Question', 'Pet-Me-Questions'), ('General-Question', 'General-Question')], max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='jobslist',
            name='jobCategories',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='jobslist',
            name='jobName',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='workingHours',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='reportingActivity',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='petfriendlyvenue',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='petfriendlyvenue',
            name='landmark',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='petfriendlyvenue',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='petfriendlyvenue',
            name='logitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='petfriendlyvenue',
            name='place',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='petfriendlyvenue',
            name='street',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='petlostfoundinfo',
            name='additionalData',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='petlostfoundinfo',
            name='additionalInfo',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='petlostfoundinfo',
            name='breed',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='petlostfoundinfo',
            name='color',
            field=models.CharField(max_length=3600),
        ),
        migrations.AlterField(
            model_name='petlostfoundinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=600),
        ),
        migrations.AlterField(
            model_name='petlostfoundinfo',
            name='typeOfPet',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='petmeservices',
            name='pets',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='petmeservices',
            name='services',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='petservices',
            name='serviceDuration',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='petservices',
            name='serviceName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='petsinfo',
            name='anythingElse',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='petsinfo',
            name='favoriteThings',
        ),
        migrations.AlterField(
            model_name='petsinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='petsinfo',
            name='petBreed',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='petsinfo',
            name='petName',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='petspersonalinfo',
            name='color',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='petspersonalinfo',
            name='identification',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='petwas',
            name='specifically',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='rescueorganizations',
            name='facebookLink',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='rescueorganizations',
            name='organizationName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rescueorganizations',
            name='webSite',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='petsinfo',
            name='favoriteThings',
            field=models.ManyToManyField(to='app.favoriteThings'),
        ),
    ]
