# Generated by Django 2.0 on 2018-11-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181112_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetinfo',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='vetinfo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vetinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='vetinfo',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vetinfo',
            name='logitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vetinfo',
            name='mobile',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vetinfo',
            name='name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vetinfo',
            name='phone',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vetinfo',
            name='workingHours',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
