# Generated by Django 2.0 on 2018-11-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181112_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetinfo',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
