# Generated by Django 2.0 on 2018-11-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rescueorganizations_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsinfo',
            old_name='favoriteThings',
            new_name='favorite',
        ),
    ]
