# Generated by Django 2.0 on 2018-11-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181113_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rescueorganizations',
            old_name='descriptions',
            new_name='description',
        ),
    ]
