# Generated by Django 2.0 on 2018-11-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181113_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='category',
            new_name='faqCategory',
        ),
    ]
