# Generated by Django 2.0 on 2018-11-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181113_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsinfo',
            name='image',
            field=models.URLField(max_length=25000, null=True),
        ),
    ]
