# Generated by Django 2.0 on 2018-11-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181113_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsinfo',
            name='image',
            field=models.CharField(max_length=25000, null=True),
        ),
    ]
