# Generated by Django 2.0 on 2018-11-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181113_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(default=1, upload_to='upload_location/'),
            preserve_default=False,
        ),
    ]
