# Generated by Django 2.0 on 2018-11-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsinfo',
            name='image',
            field=models.ImageField(default=1, upload_to='upload_location/'),
            preserve_default=False,
        ),
    ]
