# Generated by Django 2.0 on 2018-11-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20181114_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsinfo',
            name='favorite',
        ),
        migrations.AddField(
            model_name='petsinfo',
            name='favorite',
            field=models.CharField(default=1, max_length=25000),
            preserve_default=False,
        ),
    ]
