# Generated by Django 2.0 on 2018-11-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181114_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsinfo',
            name='image',
            field=models.CharField(max_length=25000, null=True),
        ),
    ]
