# Generated by Django 2.0 on 2018-11-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181114_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretakerinfo',
            name='jobExperience',
        ),
        migrations.RemoveField(
            model_name='caretakerinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ownerinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='caretakerinfo',
            name='city',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretakerinfo',
            name='first_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretakerinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretakerinfo',
            name='last_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretakerinfo',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.pet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretakerinfo',
            name='street_address',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerinfo',
            name='city',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerinfo',
            name='first_name',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=11, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerinfo',
            name='last_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerinfo',
            name='street_address',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
    ]
