# Generated by Django 2.0 on 2018-11-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20181114_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretakerinfo',
            name='pet',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='ownerinfo',
            name='pet',
            field=models.CharField(max_length=600),
        ),
    ]
