# Generated by Django 2.0 on 2018-11-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20181114_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
    ]
