# Generated by Django 2.0 on 2018-11-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlostfoundinfo',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='petlostfoundinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=5600),
        ),
        migrations.AlterField(
            model_name='petsinfo',
            name='image',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
